### model
model_name_or_path: Qwen/Qwen3-32B

### method
stage: sft
do_train: true
finetuning_type: lora
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: surveyreview_structure
dataset_dir: training/generated
template: qwen3
cutoff_len: 16384
max_samples: null
val_size: 0.1
preprocessing_num_workers: 16
overwrite_cache: true

### output
output_dir: training/outputs/Qwen3-32B/structure
overwrite_output_dir: true
logging_steps: 50
save_steps: 50
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
gradient_checkpointing: true
learning_rate: 5.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_steps: 20
fp16: true

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
load_best_model_at_end: true

### fa
flash_attn: fa2

